### ISSUE TITLE
throughtput

### ISSUE THREAD

**Issue by nd7141** [ray-project/llmperf-leaderboard#1]
Any way to add throughput results? 

P.S. Also which tool do you use to make plots like this? 

![image](https://github.com/ray-project/llmperf-leaderboard/assets/4607709/2b68b1d4-a67d-4373-9c52-72ebbc96ac70)

**Comment by jalajthanaki** [comment]
+1

**Comment by jalajthanaki** [comment]
Is it possible to get the throughput info for all the model on [LMSYS chatbot arena leaderboard](https://chat.lmsys.org/)?

I have also raised this feature request on Fastchat. https://github.com/lm-sys/FastChat/issues/2849

**Comment by richardliaw** [comment]
By throughput do you mean ratelimit/concurrent requests?

**Comment by jalajthanaki** [comment]
@richardliaw thank you for the reply. 

By throughput do you mean ratelimit/concurrent requests? - _No. Ratelimit/concurrent requests information is available for most of the proprietary LLMs/ commercialised LLM endpoints._ 

What I'm interested in is, Are there any benchmark(s) this project has around how many tokens can be generated over period of time for a given LLM, for the given fix GPU type. Something like below which vllm generates as part of the log. 

```
[llm_engine.py:649] Avg prompt throughput: 30.5 tokens/s, Avg generation throughput: 61.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%

[llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 79.2 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%

[llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 77.9 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.7%, CPU KV cache usage: 0.0%

[llm_engine.py:649] Avg prompt throughput: 122.4 tokens/s, Avg generation throughput: 72.4 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.2%, CPU KV cache usage: 0.0%

[llm_engine.py:649] Avg prompt throughput: 138.9 tokens/s, Avg generation throughput: 71.6 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%
```


Along with LLM evaluation benchmark the above throughput numbers will also help the community to further optimise and adopt right LLM for given usecase. I'm open to contribute.

**Comment by jalajthanakicactus** [comment]
@rickyyx Thank you for taking this up and raising pull request.

**Comment by ravishtiwari-labs** [comment]
+1
