### ISSUE TITLE
Configuration details

### ISSUE THREAD

**Issue by aiapprentice101** [ray-project/llmperf-leaderboard#10]
Hi, thank you for providing the benchmark. 

Can you please provide more details so we can better interpret the results. For example,
* Can you describe what GPU(s) did you use, how many of them? 
* Is there any quantization implemented? 
* Is the backend vLLM? 

Thank you.

**Comment by xieus** [comment]
The dashboard uses [llmperf benchmarking](https://github.com/ray-project/llmperf) tool to run tests over different LLM APIs.

As mentioned in the [llmperf benchmarking tool](https://github.com/ray-project/llmperf?tab=readme-ov-file#caveats-and-disclaimers) page, the backend of different API providers might vary widely, this is not a reflection on how the software (quantization or not) runs on a particular hardware (could be GPUs, CPUs or custom ASICs). Hope this helps.

**Comment by aiapprentice101** [comment]
Thank you @xieus
